#!/usr/bin/ruby -w
# Frozen_String_Literal: true
%w(erb io/console).each(&method(:require))

def main
	if file = ARGV[0]
		updated_at = 0
		print "\e[38;5;161m" + "Watching for changes to #{file}" + "\e[0m"
		output_file = File.join(__dir__, 'index.html')

		while mtime = File.mtime(file)
			w = STDOUT.winsize[1]

			if (mtime_i = mtime.to_i) > updated_at
				puts "\e[2J\e[H\e[3J", ?*.*(w / 2).center(w), "\e[1;33m" + "Updated #{file} at #{mtime}".center(w) + "\e[0m"
				updated_at = mtime_i

				begin
					erb_contents = <<~EOF
						<!Doctype HTML>
						<html>
						<!-- This file is generated by #{File.basename(Process.argv0)} -->
						<!-- Read #{file} for source code. -->
						#{ERB.new(IO.readlines(file).each(&:strip!).join(?\n)).result.split(?\n).tap { |x| x.reject!(&:empty?) }.join(?\n)}
						</html>
					EOF

					IO.write(output_file.tap { |f| puts "\e[38;5;70m" + "Updating #{f}".center(w) + "\e[0m" }, erb_contents)
					puts "\e[38;2;0;170;50m#{erb_contents}\e[0m", ?*.*(w / 2).center(w)
				rescue Exception
					puts $!
				end
			end

			sleep 0.25
		end
	end
end

begin
	main
rescue Interrupt, SystemExit, SignalException
	puts "\nGood Bye!"
rescue Exception
	abort $!.full_message
end
